Automate validation of data & push to database
soohoio/sooho-scdb pull request #1
Opened 2021-02-23 04:39 UTC by ANGJIN

## validation script

- [ ] read & parse yml 
- [ ] crawl raw function
- [ ] crawl patched function

## database push script

- [ ] implement algorithm for picking validated data
- [ ] map crawled data & yml data to DB schema
- [ ] check signature for redundant data & push to DB

2021-02-23 05:43 UTC, KOREAN139 commented on src/index.ts
> +    crawler.crawlPatchedFunc(targetYml);
`async` 함수들인데 `await` 사용을 해줘야 할 것 같습니다!

2021-02-23 05:44 UTC, KOREAN139 commented on src/crawler.ts
> +  });
이 부분도 `writeFileSync` 같은 함수를 사용하거나, `fs.promises` 패키지를 사용해서 `await fs.writeFile` 등으로 통일해주는 게 조금 더 읽기 편할 것 같습니다!

2021-02-23 06:48 UTC, ANGJIN commented on src/index.ts
> +    crawler.crawlPatchedFunc(targetYml);
확인했습니다!

2021-02-23 06:48 UTC, ANGJIN commented on src/crawler.ts
> +  });
확인했습니다~

2021-03-02 05:11 UTC, KOREAN139 requested changes
`crwalVulnerable`, `pushDb` 에서 마지막 promise들에 대한 핸들링이 되어있지 않습니다.
(`array.forEach(async funtion)` 에서 던진 error들이 핸들링 되지 않고 있습니다 / `UnhandledPromiseRejectionWarning`을 검색해보시면 좋을 것 같습니다!)

`throw error` 등으로 `catch` 블럭에서 위로 말아 올린다면, 이를 최종적으로 핸들링 한 블럭이 존재해야 합니다.

`array.map(async function)` 등으로 promise 배열을 만들고, `await Promise.all(promises)` 등으로 resolve 혹은 reject 된 값을 받아서 핸들링 하면 좋을 것 같습니다. / 혹은 위로 말아올리지 않고, async 함수 내에서 에러 처리를 해도 좋습니다!

2021-03-02 05:48 UTC, ANGJIN commented on src/crawlVulnerable.ts
> +import * as PATH from 'path';
확인후 feat/cicd branch에서 수정했습니다!

2021-03-02 05:49 UTC, ANGJIN commented on solidity/augur-002/augur-002.yml
> +---
augur-002는 invalid data test용으로 사용중인데 test에서만 사용한 data에 대해서도 feat/cicd branch에서 정리하여 구현중입니다!

2021-03-02 05:49 UTC, ANGJIN commented on src/crawlVulnerable.ts
> +    const targetVulnerable = getVulnerableDataIn(targetDirPath);
마찬가지로 feat/cicd 브랜치에 에러처리 로직 추가하겠습니다

2021-03-02 07:15 UTC, KOREAN139 approved these changes

2021-03-02 07:16 UTC, merged